// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. DIRECT_URL is only
    // set in production (Supabase); locally DATABASE_URL already points at
    // a plain local Postgres instance, so it doubles as the direct one.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
